# Generated by Django 4.2.1 on 2023-05-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_role_task_alter_workfor_role"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
