# Generated by Django 4.2.1 on 2023-06-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_invite"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="invite",
            table="invites",
        ),
    ]
