# Generated by Django 4.2.1 on 2023-06-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_invite_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="invite",
            table="invite",
        ),
    ]
