# Generated by Django 4.2.1 on 2023-06-02 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0007_alter_invite_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invites",
            },
        ),
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
