# Generated by Django 4.2.1 on 2023-05-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_task_project_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "solution_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("comments", models.TextField()),
                ("content", models.FileField(upload_to="")),
                ("post_date", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        default="deleted",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.task"
                    ),
                ),
            ],
            options={
                "db_table": "solutions",
            },
        ),
    ]
