# Generated by Django 4.2.1 on 2023-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="content",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
