# Generated by Django 4.2.1 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_solution_content_alter_solution_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="content",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
    ]
